### PR TITLE
Addition to the about page

### PR DESCRIPTION
**Pull request by AditiBendre**
Hii
Added to the about page. Changed a few things. Hope you like it. Let me know if any changes are required.

### CODE REVIEW

**Comment by preyashyadav** [comment]
Can you please share the snapshot of the part which you developed @AditiBendre

**Comment by AditiBendre** [comment]
Screenshot (1)

**Comment by AditiBendre** [comment]
Made this

**Comment by preyashyadav** [comment]
Looks beautiful, thanks!

**Pull request merged**
